#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print(np.__version__)
np.show_config

1.14.3


<function numpy.__config__.show()>

#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
array1 = np.zeros(10)
array1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array (★☆☆)

In [4]:
print(array1.size * array1.itemsize)

80


#### 5.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [6]:
array2 = np.empty(10)
array2[4] = 1
array2

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 6.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [8]:
array3 = np.arange(10,50)
array3

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 7.  Reverse a vector (first element becomes last) (★☆☆)

In [9]:
array4 = array3[::-1]
array4

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 8.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [11]:
array5 = np.arange(0,9).reshape(3,3)
array5

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 9. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [14]:
array6 = np.nonzero([1,2,0,0,4,0])
array6

(array([0, 1, 4], dtype=int64),)

#### 10. Create a 3x3 identity matrix (★☆☆)

In [13]:
array7 = np.eye(3)
array7

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 11. Create a 3x3x3 array with random values (★☆☆)

In [26]:
array8 = np.random.random((3,3,3))
array8

array([[[0.33492709, 0.93835805, 0.00290712],
        [0.70211935, 0.14997108, 0.75105924],
        [0.70100856, 0.43633987, 0.65318198]],

       [[0.25900468, 0.56733907, 0.40300222],
        [0.84622476, 0.81234704, 0.40271311],
        [0.48921613, 0.69792466, 0.50508503]],

       [[0.32573351, 0.75207435, 0.0983368 ],
        [0.8392795 , 0.92120661, 0.2848331 ],
        [0.85615664, 0.30473298, 0.72399888]]])

#### 12. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [30]:
array9 = np.random.random((10,10))
print(array9.max(),array9.min())

0.9934763833655801 0.016646623712244568


#### 13. Create a random vector of size 30 and find the mean value (★☆☆)

In [34]:
array10 = np.random.random(30)
print(array10.mean())

0.645390898690302


#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [8]:
array11 = np.ones(20).reshape(4,5)
array11

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

#### 15. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [36]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

#### 16. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [26]:
array_1 = np.arange(1,16).reshape(5,3)
array_2 = np.arange(1,7).reshape(3,2)
result = np.dot(array_1,array_2)
result

array([[ 22,  28],
       [ 49,  64],
       [ 76, 100],
       [103, 136],
       [130, 172]])

#### 17. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [11]:
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 18. How to find common values between two arrays? (★☆☆)

In [22]:
arr1 = np.random.randint(1,10,15)
arr2 = np.random.randint(1,10,15)
np.intersect1d(arr1,arr2)

array([1, 2, 3, 5, 6, 7])